version: "3"
services:
  db:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=figures
      - POSTGRES_PASSWORD=s3cr3t
      - POSTGRES_DB=figurearchive
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data