spring:
  jpa:
    hibernate:
      ddl-auto: none
  database:
    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/figurearchive
    username: figures
    password: s3cr3t

  servlet:
    multipart:
      enabled: false  # needs to be disabled because of vaadin-upload bug

tumblr:
  consumer-key: ${API_KEY}
  consumer-secret: ${API_SECRET}

figurearchive:
  admin-password: ${ADMIN_PASSWORD}
  tumblr:
    initialize: true
  figures:
    page-size: 1000
  photos:
    page-size: 5000

---

spring:
  profiles: heroku
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}