INSERT INTO product_line (code, description, year_started) VALUES ('KENNER', 'Vintage Kenner', 1977);
INSERT INTO product_line (code, description, year_started) VALUES ('POTF2', 'Power of the Force 2', 1995);
INSERT INTO product_line (code, description, year_started) VALUES ('POTJ', 'Power of the Jedi', 2000);
INSERT INTO product_line (code, description, year_started) VALUES ('SOTE', 'Shadows of the Empire', 1996);
INSERT INTO product_line (code, description, year_started) VALUES ('EPISODE1', 'Episode 1', 1999);
INSERT INTO product_line (code, description, year_started) VALUES ('SAGA', 'Saga', 2002);
INSERT INTO product_line (code, description, year_started) VALUES ('DC', 'Disney Collection', 2002);
INSERT INTO product_line (code, description, year_started) VALUES ('OCW', 'Clone Wars', 2003);
INSERT INTO product_line (code, description, year_started) VALUES ('CWANIMATED', 'Clone Wars Animated Style', 2003);
INSERT INTO product_line (code, description, year_started) VALUES ('OTC', 'Original Trilogy Collection', 2004);
INSERT INTO product_line (code, description, year_started) VALUES ('ROTS', 'Revenge of the Sith', 2005);
INSERT INTO product_line (code, description, year_started) VALUES ('TSC', 'The Saga Collection', 2006);
INSERT INTO product_line (code, description, year_started) VALUES ('TAC', 'The Anniversary Collection', 2007);
INSERT INTO product_line (code, description, year_started) VALUES ('TLC', 'The Legacy Collection', 2008);
INSERT INTO product_line (code, description, year_started) VALUES ('TCW', 'The Clone Wars', 2008);
INSERT INTO product_line (code, description, year_started) VALUES ('SOTDS', 'Shadow of the Dark Side', 2010);
INSERT INTO product_line (code, description, year_started) VALUES ('TVC', 'The Vintage Collection', 2010);
INSERT INTO product_line (code, description, year_started) VALUES ('DTF', 'Discover the Force', 2012);
INSERT INTO product_line (code, description, year_started) VALUES ('MH', 'Movie Heroes', 2012);
INSERT INTO product_line (code, description, year_started) VALUES ('TLC13', 'The Legacy Collection 2013', 2013);
INSERT INTO product_line (code, description, year_started) VALUES ('SL', 'Saga Legends', 2013);
INSERT INTO product_line (code, description, year_started) VALUES ('TBS', 'The Black Series', 2013);
INSERT INTO product_line (code, description, year_started) VALUES ('TBS6', 'The Black Series 6"', 2013);
INSERT INTO product_line (code, description, year_started) VALUES ('SWR', 'Star Wars Rebels Saga Legends', 2014);
INSERT INTO product_line (code, description, year_started) VALUES ('TFA', 'The Force Awakens', 2015);
INSERT INTO product_line (code, description, year_started) VALUES ('RO', 'Rogue One', 2016);
INSERT INTO product_line (code, description, year_started) VALUES ('TLJ', 'The Last Jedi', 2017);
INSERT INTO product_line (code, description, year_started) VALUES ('SOLO', 'Solo: A Star Wars Story', 2018);
INSERT INTO product_line (code, description, year_started) VALUES ('GOA', 'Galaxy of Adventures 3.75"', 2019);
INSERT INTO product_line (code, description, year_started) VALUES ('GOA5', 'Galaxy of Adventures 5" Animated Style', 2019);
INSERT INTO product_line (code, description, year_started) VALUES ('RESISTANCE', 'Star Wars Resistance', 2019);
INSERT INTO product_line (code, description, year_started) VALUES ('RETRO', 'Retro Collection', 2019);
INSERT INTO product_line (code, description, year_started) VALUES ('MISSIONFLEET', 'Mission Fleet Series', null);
INSERT INTO product_line (code, description, year_started) VALUES ('SHFIGUARTS', 'SH Figuarts', null);
INSERT INTO product_line (code, description, year_started) VALUES ('BANDAI', 'Bandai Model Kit', null);
INSERT INTO product_line (code, description, year_started) VALUES ('HERO', '12" Hero Series', null);
INSERT INTO product_line (code, description, year_started) VALUES ('GGJ', '12" Gentle Giant Jumbo', null);
